{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gggenes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gggenes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gggenes/gggenes_{{ version }}.tar.gz
  sha256: e91971b7fefa74c0f0c62c5f9128a8fec6e9f3f7107b6db8400424132b5a17a6

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggfittext >=0.4.3
    - r-ggplot2 >=2.2.1
    - r-rlang >=0.2.0
  run:
    - r-base
    - r-ggfittext >=0.4.3
    - r-ggplot2 >=2.2.1
    - r-rlang >=0.2.0

test:
  commands:
    - $R -e "library('gggenes')"           # [not win]
    - "\"%R%\" -e \"library('gggenes')\""  # [win]

about:
  home: https://github.com/wilkox/gggenes
  license: GPL-2
  summary: Provides a 'ggplot2' geom and helper functions for drawing gene arrow maps.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gggenes
# Title: Draw Gene Arrow Maps in 'ggplot2'
# Version: 0.3.2
# Authors@R: person("David", "Wilkins", email = "david@wilkox.org", role = c("aut", "cre"))
# Description: Provides a 'ggplot2' geom and helper functions for drawing gene arrow maps.
# Depends: R (>= 3.3.0)
# Imports: grid (>= 3.3.0), ggplot2 (>= 2.2.1), ggfittext (>= 0.4.3), rlang (>= 0.2.0)
# License: GPL-2
# LazyData: true
# RoxygenNote: 6.1.0
# URL: https://github.com/wilkox/gggenes
# BugReports: https://github.com/wilkox/gggenes/issues
# Suggests: testthat, knitr, rmarkdown, vdiffr
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-11-07 08:50:45 UTC; wilkox
# Author: David Wilkins [aut, cre]
# Maintainer: David Wilkins <david@wilkox.org>
# Repository: CRAN
# Date/Publication: 2018-11-07 09:10:03 UTC
