{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gggenes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gggenes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gggenes/gggenes_{{ version }}.tar.gz
  sha256: 09d3af8aa11a7bd4ec84b67036727188301942574cd78d0be7880e08fb53de1b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggfittext >=0.8.0
    - r-ggplot2 >=2.2.1
    - r-rlang >=0.2.0
  run:
    - r-base
    - r-ggfittext >=0.8.0
    - r-ggplot2 >=2.2.1
    - r-rlang >=0.2.0

test:
  commands:
    - $R -e "library('gggenes')"           # [not win]
    - "\"%R%\" -e \"library('gggenes')\""  # [win]

about:
  home: https://wilkox.org/gggenes
  license: GPL-2.0-only
  summary: Provides a 'ggplot2' geom and helper functions for drawing gene arrow maps.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gggenes
# Title: Draw Gene Arrow Maps in 'ggplot2'
# Version: 0.4.0
# Authors@R: c(person("David", "Wilkins", email = "david@wilkox.org", role = c("aut", "cre")), person("Zachary", "Kurtz", email = "zdkurtz@gmail.com", role = c("ctb")))
# Description: Provides a 'ggplot2' geom and helper functions for drawing gene arrow maps.
# Depends: R (>= 3.3.0)
# Imports: grid (>= 3.3.0), ggplot2 (>= 2.2.1), ggfittext (>= 0.8.0), rlang (>= 0.2.0)
# License: GPL-2
# LazyData: true
# RoxygenNote: 6.1.1
# URL: https://wilkox.org/gggenes
# BugReports: https://github.com/wilkox/gggenes/issues
# Suggests: testthat, knitr, rmarkdown, vdiffr
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-06-24 02:56:09 UTC; wilkox
# Author: David Wilkins [aut, cre], Zachary Kurtz [ctb]
# Maintainer: David Wilkins <david@wilkox.org>
# Repository: CRAN
# Date/Publication: 2019-06-24 05:10:11 UTC
