travis:
  secure:
    BINSTAR_TOKEN: jrrpbviX2TwDfDI3lXm1P1Z5fl53ooECH5kF+dX0Z5blWWkOXizprIeixOSoJvblyE0vmKOC8gS1TvSa0dl5oKzdH9hUX9XSnACs6wbC6EkSKo5QeqkonajNt29Dv0XE8b0GpWnKDXfoHS9eQ5/64XLZmp6N27YE4//GoVY9oSl4rw/ATXcWQOPXmEIiYG2jDf1m/o5SaSen0D4wXJbD3aanoiDPvROdi3VxGqGE63xFJATDphYshdKQnMdw1XnSi57OBQo6o0p0Ernr2kETIdu0qEPYtLnQ6CrzkdDlJn6kXx8SYBRK44RLKoCmz1WBfpULbGlYGpfjqdE1lT4WhkYA2wpuk1vZyEfV5MR6lQkNcllfK4GQX0f36w4xOhaF5s9mQtsbsjBrUUsqoZJTtbZpcuTK8a+nErP/dLCuBFiW0SY3UIrelmUaFaW4G+6y14GnVcMqSFCrdpV7NELhU+X/M8ugG6JIT5bGzXC18Hf86LhsSbWglNXL16PlZ3vlp0L64ncBpIS+fDLGgSpFEpw+KSy5aRIZoM16IPensOmHMa74DyBwAS1xmoEf5C5jgzrGmzgVG0dPEjvZLWPU+aRl2pzueCqfn7J+An8pk6PNXq/vmJ7l7pgRQC0D3LPujPYjGT73dV2mvCySZeGCwd112EV2u5KfYWakNjyvFz8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
